steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        pwd
        cd /home/jeya_priya_c/terraform-google-vm/examples/compute_instance/simple/
        terraform init
        terraform validate
        terraform plan -out terraform.plan
        terraform apply terraform.plan
     
     
