steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        pwd
        ls -lrt
        df -h
        cd /workspace/examples/compute_instance/simple/
        pwd
        terraform init
        terraform validate
        terraform plan -out terraform.plan
        terraform apply terraform.plan
     
     
