steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        cd /home/jeya_priya_c/terraform-google-vm/examples/compute_instance/simple
        echo "run init"
        terraform init
        echo "run validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply terraform.plan
     
